#!/usr/bin/env php
<?php

use CatPaw\Environment\Attributes\Environment;
use CatPaw\Environment\Attributes\EnvironmentFileName;
use CatPaw\Environment\Services\EnvironmentService;

use function Amp\File\read;

#[EnvironmentFileName('.env.yml')]
function main(
    #[Environment('projects')] array $projects,
){
    chdir(dirname(__FILE__));
    $root = realpath('../../');

    chdir("$root/catpaw-dev-tools");
    echo "Purging tags of catpaw-dev-tools".PHP_EOL;
    `git tag -l | xargs git tag -d`;
    `git fetch`;
    `git tag -l | xargs git push --delete origin`;
    `git tag -l | xargs git tag -d`;

    foreach($projects as $project){
        chdir("$root/catpaw-$project");
        echo "Purging tags of catpaw-$project".PHP_EOL;
        `git tag -l | xargs git tag -d`;
        `git fetch`;
        `git tag -l | xargs git push --delete origin`;
        `git tag -l | xargs git tag -d`;
    }
}
