master: .

exports:
  - "bin"
  - ".vscode"
  - ".github"
  - ".php-cs-fixer.php"
  - "psalm.xml"
  - "build.yml"
  - "LICENSE"
  - ".gitignore"
  - "CODE_OF_CONDUCT.md"
  - "CONTRIBUTING.md"
web-server:
  interfaces: 
    - 127.0.0.1:8080
projects:
  .:
    library: catpaw/dev-tools
    version: 0.4.104
  ../catpaw-core:
    library: catpaw/core
    version: 0.4.104
  ../catpaw-libsdl:
    library: catpaw/libsdl
    version: 0.4.104
  ../catpaw-web:
    library: catpaw/web
    version: 0.4.104
  ../catpaw-cli:
    library: catpaw/cli
    version: 0.4.104
  ../catpaw-examples:
    library: catpaw/examples
    version: 0.4.104
  ../catpaw-mysql:
    library: catpaw/mysql
    version: 0.4.104
  ../catpaw-mysql-dbms:
    library: catpaw/mysql-dbms
    version: 0.4.104
  ../catpaw-optional:
    library: catpaw/optional
    version: 0.4.104
  ../catpaw-queue:
    library: catpaw/queue
    version: 0.4.104
  ../catpaw-raspberrypi:
    library: catpaw/raspberrypi
    version: 0.4.104
  ../catpaw-store:
    library: catpaw/store
    version: 0.4.104
  ../catpaw-cui:
    library: catpaw/cui
    version: 0.4.104
  ../catpaw-spa:
    library: catpaw/spa
    version: 0.4.104
  ../catpaw-starter:
    library: catpaw/starter
    version: 0.4.104
  ../catpaw-web-starter:
    library: catpaw/web-starter
    version: 0.4.104
  ../catpaw-svelte-starter:
    library: catpaw/svelte-starter
    version: 0.4.104
    imports:
      - "bin"
      - ".gitignore"
      - ".github"
      - ".php-cs-fixer.php"
      - "psalm.xml"
      - "build.yml"
      - "LICENSE"
      - "CODE_OF_CONDUCT.md"
      - "CONTRIBUTING.md"
