#!/usr/bin/env php
<?php
use function Amp\call;
use function Amp\File\createDirectoryRecursively;
use function Amp\File\exists;
use function Amp\File\isFile;
use Amp\Promise;
use CatPaw\Environment\Attributes\Environment;
use CatPaw\Environment\Attributes\EnvironmentFileName;

use function CatPaw\copyDirectoryRecursively;

use function CatPaw\copyFile;
use function CatPaw\deleteDirectoryRecursively;

function export(string $project, array $items):Promise {
    return call(function() use ($project, $items) {
        foreach ($items as $item) {
            $source      = "./$item";
            $destination = "../catpaw-$project/$item";
            if (!yield exists($source)) {
                echo "Skipping source file \"$source\" because it doesn't exist.".PHP_EOL;
                continue;
            }
            if (yield isFile($source)) {
                $ddirname = dirname($destination);
                if (!yield exists($ddirname)) {
                    yield createDirectoryRecursively($ddirname);
                }
                yield copyFile($source, $destination);
                continue;
            }
            if (yield exists($destination)) {
                yield deleteDirectoryRecursively($destination);
            }
            yield copyDirectoryRecursively($source, $destination);
        }
    });
}


/**
 * 
 * @param array{
 *  dev-tools: array{
 *   version: string,
 *   message: string
 *  },
 *  core: array{
 *   version: string,
 *   message: string
 *  },
 *  cli: array{
 *   version: string,
 *   message: string
 *  },
 *  environment: array{
 *   version: string,
 *   message: string
 *  },
 *  examples: array{
 *   version: string,
 *   message: string
 *  },
 *  mysql: array{
 *   version: string,
 *   message: string
 *  },
 *  mysql-dbms: array{
 *   version: string,
 *   message: string
 *  },
 *  optional: array{
 *   version: string,
 *   message: string
 *  },
 *  queue: array{
 *   version: string,
 *   message: string
 *  },
 *  raspberrypi: array{
 *   version: string,
 *   message: string
 *  },
 *  starter: array{
 *   version: string,
 *   message: string
 *  },
 *  store: array{
 *   version: string,
 *   message: string
 *  },
 *  web: array{
 *   version: string,
 *   message: string
 *  },
 *  cui: array{
 *   version: string,
 *   message: string
 *  },
 *  spa: array{
 *   version: string,
 *   message: string
 *  },
 *  web-starter: array{
 *   version: string,
 *   message: string
 *  },
 *  svelte-starter: array{
 *   version: string,
 *   message: string
 *  }
 * } $projects 
 * @return void 
 * @throws Error 
 */
#[EnvironmentFileName('.env.yml')]
function main(
    #[Environment('projects')] array $projects,
) {
    chdir(dirname(__FILE__));
    foreach($projects as $project => $options){
        if($project === "dev-tools"){
            // skip self
            continue;
        }
        yield export($project, match($project){
            "svelte-starter" => ['bin','.github','start','.php-cs-fixer.php'],
            default => ['bin','.vscode','.github','start','.php-cs-fixer.php'],
        });
    }
}
